import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { createClient } from "@hey-api/openapi-ts";

import { normalizeSpec } from "../src/codegen/normalize";

const ATTIO_OPENAPI_URL = "https://api.attio.com/openapi/api";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const generatedDir = path.join(repoRoot, "src", "generated");
const manifestPath = path.join(generatedDir, "manifest.gen.ts");

const renderManifestModule = (manifest: unknown): string => `// This file is auto-generated by scripts/generate.ts

import type { OperationManifest } from "../manifest-types";

export const manifest = ${JSON.stringify(manifest, null, 2)} satisfies OperationManifest[];
`;

const fetchSpec = async (): Promise<unknown> => {
  const response = await fetch(process.env.ATTIO_OPENAPI_URL ?? ATTIO_OPENAPI_URL);
  if (!response.ok) {
    throw new Error(`Failed to fetch the Attio OpenAPI spec: ${response.status}`);
  }
  return response.json();
};

const main = async (): Promise<void> => {
  const spec = await fetchSpec();
  const manifest = normalizeSpec(spec as { paths: Record<string, Record<string, unknown>> });

  await rm(generatedDir, { recursive: true, force: true });
  await mkdir(generatedDir, { recursive: true });

  await createClient({
    input: spec as Parameters<typeof createClient>[0] extends infer T
      ? T extends { input?: infer I }
        ? I
        : never
      : never,
    output: generatedDir,
  });

  await writeFile(manifestPath, renderManifestModule(manifest), "utf8");

  process.stdout.write(`Generated ${manifest.length} Attio operations in src/generated\n`);
};

await main();
