import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { createClient, type UserConfig } from "@hey-api/openapi-ts";

import {
  applySyntheticOperationIds,
  normalizeSpec,
  type OpenApiObject,
} from "../src/codegen/normalize";

const ATTIO_OPENAPI_URL = "https://api.attio.com/openapi/api";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const generatedDir = path.join(repoRoot, "src", "generated");
const manifestPath = path.join(generatedDir, "manifest.gen.ts");

const renderManifestModule = (
  manifest: unknown,
): string => `// This file is auto-generated by scripts/generate.ts

import type { OperationManifest } from "../manifest-types";

export const manifest = ${JSON.stringify(manifest, null, 2)} satisfies OperationManifest[];
`;

const fetchSpec = async (): Promise<unknown> => {
  const response = await fetch(
    process.env.ATTIO_OPENAPI_URL ?? ATTIO_OPENAPI_URL,
  );
  if (!response.ok) {
    throw new Error(
      `Failed to fetch the Attio OpenAPI spec: ${response.status}`,
    );
  }
  return response.json();
};

const patchSpec = (spec: OpenApiObject): void => {
  applySyntheticOperationIds(spec);
};

const main = async (): Promise<void> => {
  const spec = (await fetchSpec()) as OpenApiObject;
  patchSpec(spec);
  const manifest = normalizeSpec(spec);

  await rm(generatedDir, { recursive: true, force: true });
  await mkdir(generatedDir, { recursive: true });

  await createClient({
    input: spec as UserConfig["input"],
    output: generatedDir,
    parser: {
      patch: {
        input: (openApi) => {
          patchSpec(openApi as OpenApiObject);
        },
      },
    },
  });

  await writeFile(manifestPath, renderManifestModule(manifest), "utf8");

  process.stdout.write(
    `Generated ${manifest.length} Attio operations in src/generated\n`,
  );
};

await main();
